<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\RouteDefinition;
use AIProjectScanner\DTO\RouteDiscoveryResult;

final class ApiRoutesGenerator
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {
    }

    public function generate(
        RouteDiscoveryResult $result,
        string $outputDirectory
    ): void {
        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::API_ROUTES,
            $this->buildContent($result)
        );
    }

    private function buildContent(RouteDiscoveryResult $result): string
    {
        $lines = [
            '# API Routes',
            '',
            'Generated by AI Project Scanner.',
            '',
        ];

        if (!$result->hasRoutes()) {
            $lines[] = 'No API routes detected.';
            $lines[] = '';

            return implode(PHP_EOL, $lines);
        }

        $routesByFramework = [];

        foreach ($result->getRoutes() as $route) {
            if (!$route instanceof RouteDefinition) {
                continue;
            }

            $routesByFramework[$route->getFramework()][] = $route;
        }

        ksort($routesByFramework);

        foreach ($routesByFramework as $framework => $routes) {
            $lines[] = '## ' . $framework;
            $lines[] = '';
            $lines[] = '| Method | URI | Handler |';
            $lines[] = '|--------|-----|---------|';

            foreach ($routes as $route) {
                $lines[] = '| ' . $route->getMethod() . ' | ' . $route->getUri() . ' | ' . $route->getHandler() . ' |';
            }

            $lines[] = '';
        }

        return implode(PHP_EOL, $lines);
    }
}