<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\FrameworkDetectionResult;

final class FrameworksGenerator
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {
    }

    public function generate(
        FrameworkDetectionResult $result,
        string $outputDirectory
    ): void {
        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::FRAMEWORKS,
            $this->buildContent($result)
        );
    }

    private function buildContent(FrameworkDetectionResult $result): string
    {
        $frameworks = $result->getFrameworks();

        $lines = [
            '# Detected Frameworks',
            '',
            'Generated by AI Project Scanner.',
            '',
            '## Frameworks',
            '',
        ];

        if ($frameworks === []) {
            $lines[] = 'No frameworks detected.';
            $lines[] = '';

            return implode(PHP_EOL, $lines);
        }

        foreach ($frameworks as $framework) {
            $lines[] = '- ' . $framework;
        }

        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }
}