<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\ProjectStructureResult;

final class ProjectStructureGenerator
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {
    }

    public function generate(
        ProjectStructureResult $result,
        string $outputDirectory
    ): void {

        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::PROJECT_STRUCTURE,
            $this->buildContent($result)
        );
    }

    private function buildContent(
        ProjectStructureResult $result
    ): string {

        return implode(PHP_EOL, [
            '# Project Structure',
            '',
            'Generated by AI Project Scanner.',
            '',
            $this->buildSection(
                'Backend Entry Points',
                $result->getBackendEntryPoints()
            ),

            $this->buildSection(
                'Frontend Entry Points',
                $result->getFrontendEntryPoints()
            ),

            $this->buildSection(
                'Route Files',
                $result->getRouteFiles()
            ),

            $this->buildSection(
                'Controller Files',
                $result->getControllerFiles()
            ),

            $this->buildSection(
                'Service Files',
                $result->getServiceFiles()
            ),

            $this->buildSection(
                'Model Files',
                $result->getModelFiles()
            ),

            $this->buildSection(
                'Database Files',
                $result->getDatabaseFiles()
            ),

            $this->buildSection(
                'Configuration Files',
                $result->getConfigFiles()
            ),

            $this->buildSection(
                'Test Files',
                $result->getTestFiles()
            ),

            $this->buildSection(
                'Documentation Files',
                $result->getDocumentationFiles()
            ),

            $this->buildSection(
                'Deployment Files',
                $result->getDeploymentFiles()
            ),
        ]);
    }

    private function buildSection(
        string $title,
        array $items
    ): string {

        $content = [
            "## {$title}",
            '',
        ];

        if ($items === []) {
            $content[] = '- None detected';
        } else {
            foreach ($items as $item) {
                $content[] = '- ' . $item;
            }
        }

        $content[] = '';

        return implode(PHP_EOL, $content);
    }
}