<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\FrameworkDetectionResult;
use AIProjectScanner\DTO\ProjectStructureResult;
use AIProjectScanner\DTO\ScanResult;

final class ProjectContextGenerator
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {
    }

    public function generate(
        ScanResult $scanResult,
        FrameworkDetectionResult $frameworkResult,
        ProjectStructureResult $structureResult,
        string $outputDirectory
    ): void {
        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::PROJECT_CONTEXT,
            $this->buildContent($scanResult, $frameworkResult, $structureResult)
        );
    }

    private function buildContent(
        ScanResult $scanResult,
        FrameworkDetectionResult $frameworkResult,
        ProjectStructureResult $structureResult
    ): string {
        return implode(PHP_EOL, [
            '# Project Context',
            '',
            'Generated by AI Project Scanner.',
            '',
            '## Purpose',
            '',
            'This document gives AI assistants a high-level understanding of the project before making code changes.',
            '',
            '## Project Summary',
            '',
            '- Project: ' . $scanResult->getProjectName(),
            '- Total Directories: ' . count($scanResult->getDirectories()),
            '- Total Files: ' . count($scanResult->getFiles()),
            '- Ignored Paths: ' . count($scanResult->getIgnored()),
            '- Errors: ' . count($scanResult->getErrors()),
            '',
            '## Detected Frameworks',
            '',
            $this->buildFrameworkList($frameworkResult),
            '',
            '## Important Directories',
            '',
            $this->buildImportantDirectories($structureResult),
            '',
            '## Important Files',
            '',
            $this->buildImportantFiles($structureResult),
            '',
            '## AI Guidance',
            '',
            '- Start with this file before reading detailed project files.',
            '- Use PROJECT_TREE.md to understand folder structure.',
            '- Use PROJECT_MAP.json for complete file metadata.',
            '- Use SCAN_REPORT.md for file statistics and ignored paths.',
            '- Use FRAMEWORKS.md for detected technology stack.',
            '- Use PROJECT_STRUCTURE.md to understand entry points, routes, controllers, services, models, database files, config, tests, documentation, and deployment files.',
            '- Before suggesting code changes, identify related controller, model, service, route, API, database, frontend, and test files.',
            '- Avoid modifying vendor, node_modules, build, dist, cache, framework internals, and generated files.',
            '- Prefer small, focused changes with clear reasoning.',
            '',
        ]);
    }

    private function buildFrameworkList(FrameworkDetectionResult $frameworkResult): string
    {
        if ($frameworkResult->getFrameworks() === []) {
            return 'No frameworks detected.';
        }

        return implode(
            PHP_EOL,
            array_map(
                fn (string $framework): string => '- ' . $framework,
                $frameworkResult->getFrameworks()
            )
        );
    }

    private function buildImportantDirectories(ProjectStructureResult $structureResult): string
    {
        $directories = [];

        foreach ($this->getStructureGroups($structureResult) as $group) {
            foreach ($group as $file) {
                $directory = dirname($file);

                if ($directory !== '.' && $directory !== '') {
                    $directories[] = str_replace('\\', '/', $directory);
                }
            }
        }

        $directories = array_values(array_unique($directories));
        sort($directories);

        if ($directories === []) {
            return 'No important directories detected.';
        }

        return implode(
            PHP_EOL,
            array_map(
                fn (string $directory): string => '- ' . $directory,
                $directories
            )
        );
    }

    private function buildImportantFiles(ProjectStructureResult $structureResult): string
    {
        $files = [];

        foreach ($this->getStructureGroups($structureResult) as $group) {
            foreach ($group as $file) {
                $files[] = $file;
            }
        }

        $files = array_values(array_unique($files));
        sort($files);

        if ($files === []) {
            return 'No important files detected.';
        }

        return implode(
            PHP_EOL,
            array_map(
                fn (string $file): string => '- ' . $file,
                $files
            )
        );
    }

    /**
     * @return array<int, array<string>>
     */
    private function getStructureGroups(ProjectStructureResult $structureResult): array
    {
        return [
            $structureResult->getBackendEntryPoints(),
            $structureResult->getFrontendEntryPoints(),
            $structureResult->getRouteFiles(),
            $structureResult->getControllerFiles(),
            $structureResult->getServiceFiles(),
            $structureResult->getModelFiles(),
            $structureResult->getDatabaseFiles(),
            $structureResult->getConfigFiles(),
            $structureResult->getTestFiles(),
            $structureResult->getDocumentationFiles(),
            $structureResult->getDeploymentFiles(),
        ];
    }
}