<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\FrameworkDetectionResult;
use AIProjectScanner\DTO\ScanResult;

final class ProjectContextGenerator
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {
    }

    public function generate(
        ScanResult $scanResult,
        FrameworkDetectionResult $frameworkResult,
        string $outputDirectory
    ): void {
        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::PROJECT_CONTEXT,
            $this->buildContent($scanResult, $frameworkResult)
        );
    }

    private function buildContent(
        ScanResult $scanResult,
        FrameworkDetectionResult $frameworkResult
    ): string {
        return implode(PHP_EOL, [
            '# Project Context',
            '',
            'Generated by AI Project Scanner.',
            '',
            '## Purpose',
            '',
            'This document gives AI assistants a high-level understanding of the project before making code changes.',
            '',
            '## Project Summary',
            '',
            '- Project: ' . $scanResult->getProjectName(),
            '- Total Directories: ' . count($scanResult->getDirectories()),
            '- Total Files: ' . count($scanResult->getFiles()),
            '- Ignored Paths: ' . count($scanResult->getIgnored()),
            '- Errors: ' . count($scanResult->getErrors()),
            '',
            '## Detected Frameworks',
            '',
            $this->buildFrameworkList($frameworkResult),
            '',
            '## Important Directories',
            '',
            $this->buildImportantDirectories($scanResult),
            '',
            '## Important Files',
            '',
            $this->buildImportantFiles($scanResult),
            '',
            '## AI Guidance',
            '',
            '- Start with this file before reading detailed project files.',
            '- Use PROJECT_TREE.md to understand folder structure.',
            '- Use PROJECT_MAP.json for complete file metadata.',
            '- Use SCAN_REPORT.md for file statistics and ignored paths.',
            '- Use FRAMEWORKS.md for detected technology stack.',
            '- Before suggesting code changes, identify related controller, model, view, route, API, and frontend files.',
            '- Avoid modifying vendor, node_modules, build, dist, cache, and generated files.',
            '- Prefer small, focused changes with clear reasoning.',
            '',
        ]);
    }

    private function buildFrameworkList(FrameworkDetectionResult $frameworkResult): string
    {
        if ($frameworkResult->getFrameworks() === []) {
            return 'No frameworks detected.';
        }

        return implode(
            PHP_EOL,
            array_map(
                fn (string $framework): string => '- ' . $framework,
                $frameworkResult->getFrameworks()
            )
        );
    }

    private function buildImportantDirectories(ScanResult $scanResult): string
    {
        $important = [
            'app/Controllers',
            'app/Models',
            'app/Views',
            'app/Config',
            'app/Database',
            'routes',
            'src',
            'src/components',
            'src/features',
            'src/pages',
            'react/src',
            'react/src/components',
            'react/src/features',
            'react/src/pages',
        ];

        $found = [];

        foreach ($scanResult->getDirectories() as $directory) {
            $path = $directory->getPath();

            if (in_array($path, $important, true)) {
                $found[] = $path;
            }
        }

        if ($found === []) {
            return 'No standard important directories detected.';
        }

        sort($found);

        return implode(
            PHP_EOL,
            array_map(
                fn (string $path): string => '- ' . $path,
                $found
            )
        );
    }

    private function buildImportantFiles(ScanResult $scanResult): string
    {
        $importantFiles = [
            'composer.json',
            'package.json',
            'react/package.json',
            'app/Config/Routes.php',
            'routes/web.php',
            'routes/api.php',
            'artisan',
            'spark',
            'index.php',
            'public/index.php',
            'vite.config.js',
            'react/vite.config.js',
        ];

        $found = [];

        foreach ($scanResult->getFiles() as $file) {
            $path = $file->getPath();

            if (in_array($path, $importantFiles, true)) {
                $found[] = $path;
            }
        }

        if ($found === []) {
            return 'No standard important files detected.';
        }

        sort($found);

        return implode(
            PHP_EOL,
            array_map(
                fn (string $path): string => '- ' . $path,
                $found
            )
        );
    }
}