<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Contracts\GeneratorInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\AnalysisSummary;
use AIProjectScanner\DTO\FileNode;
use AIProjectScanner\DTO\ScanResult;

final class ScanReportGenerator implements GeneratorInterface
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {}

    public function generate(
        ScanResult $result,
        string $outputDirectory,
        ?AnalysisSummary $analysisSummary = null
    ): void {
        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::SCAN_REPORT,
            $this->buildContent($result,$analysisSummary)
        );
    }

    private function buildContent(ScanResult $result, AnalysisSummary $analysisSummary = null): string
    {
        return implode(PHP_EOL, [
            '# Scan Report',
            '',
            'Generated by AI Project Scanner.',
            '## Analysis Statistics',
            '',
            $this->buildAnalysisSummary($analysisSummary),
            '',
            '',
            '## Summary',
            '',
            '- Project: ' . $result->getProjectName(),
            '- Total Directories: ' . count($result->getDirectories()),
            '- Total Files: ' . count($result->getFiles()),
            '- Ignored Paths: ' . count($result->getIgnored()),
            '- Errors: ' . count($result->getErrors()),
            '',
            '## File Extensions',
            '',
            $this->buildExtensionTable($result),
            '',
            '## Ignored Paths',
            '',
            $this->buildIgnoredList($result),
            '',
            '## Errors',
            '',
            $this->buildErrorsList($result),
            '',
        ]);
    }

    private function buildExtensionTable(ScanResult $result): string
    {
        $extensions = [];

        foreach ($result->getFiles() as $file) {
            if (!$file instanceof FileNode) {
                continue;
            }

            $extension = $file->getExtension() !== ''
                ? $file->getExtension()
                : '[no extension]';

            $extensions[$extension] = ($extensions[$extension] ?? 0) + 1;
        }

        ksort($extensions);

        $rows = [
            '| Extension | Count |',
            '|-----------|-------|',
        ];

        foreach ($extensions as $extension => $count) {
            $rows[] = '| ' . $extension . ' | ' . $count . ' |';
        }

        return implode(PHP_EOL, $rows);
    }

    private function buildIgnoredList(ScanResult $result): string
    {
        $ignored = array_unique(
            array_map(
                fn(string $path): string => strtok($path, '/') ?: $path,
                $result->getIgnored()
            )
        );

        sort($ignored);

        if ($ignored === []) {
            return 'No ignored paths.';
        }

        return implode(
            PHP_EOL,
            array_map(
                fn(string $path): string => '- ' . $path,
                $ignored
            )
        );
    }

    private function buildErrorsList(ScanResult $result): string
    {
        if ($result->getErrors() === []) {
            return 'No errors detected.';
        }

        return implode(
            PHP_EOL,
            array_map(
                fn(string $error): string => '- ' . $error,
                $result->getErrors()
            )
        );
    }

    private function buildAnalysisSummary(
        ?AnalysisSummary $analysisSummary
    ): string {
        if ($analysisSummary === null) {
            return 'No analysis statistics available.';
        }

        $rows = [
            '- Total Routes: ' . $analysisSummary->getRouteCount(),
        ];

        foreach (
            $analysisSummary->getFrameworkRouteCounts()
            as $framework => $count
        ) {
            $rows[] = '- ' . $framework . ' Routes: ' . $count;
        }

        return implode(PHP_EOL, $rows);
    }
}
