<?php

declare(strict_types=1);

namespace AIProjectScanner\Generator;

use AIProjectScanner\Contracts\FileSystemInterface;
use AIProjectScanner\Contracts\GeneratorInterface;
use AIProjectScanner\Core\Constants;
use AIProjectScanner\DTO\DirectoryNode;
use AIProjectScanner\DTO\FileNode;
use AIProjectScanner\DTO\ScanResult;

final class TreeGenerator implements GeneratorInterface
{
    public function __construct(
        private readonly FileSystemInterface $fileSystem
    ) {
    }

    public function generate(
        ScanResult $result,
        string $outputDirectory
    ): void {
        $this->fileSystem->ensureDirectoryExists($outputDirectory);

        $this->fileSystem->write(
            $outputDirectory . DIRECTORY_SEPARATOR . Constants::PROJECT_TREE,
            $this->buildContent($result)
        );
    }

    private function buildContent(ScanResult $result): string
    {
        $paths = [];

        foreach ($result->getDirectories() as $directory) {
            if ($directory instanceof DirectoryNode) {
                $paths[] = rtrim($directory->getPath(), '/') . '/';
            }
        }

        foreach ($result->getFiles() as $file) {
            if ($file instanceof FileNode) {
                $paths[] = $file->getPath();
            }
        }

        sort($paths);

        return implode(PHP_EOL, [
            '# Project Tree',
            '',
            'Generated by AI Project Scanner.',
            '',
            '```text',
            $result->getProjectName(),
            ...array_map(
                fn (string $path): string => '  ' . $path,
                $paths
            ),
            '```',
            '',
        ]);
    }
}